### ISSUE TITLE
module will not load

### ISSUE THREAD

**Issue by Markdf68** [rafhtl/MMM-rdrDrawingBoard#2]
Thank you very much for writing this Module.
I really like this idea and it would be awesome to be able to use the module, 
I am trying to use the module but i get an error and MagicMirror will not open with the code in in the Config.js file
(node:2715) UnhandledPromiseRejectionWarning: Error: Cannot find module 'request'
Require stack:
- 
- /MagicMirror/modules/MMM-rdrDrawingBoard/node_helper.js
- /MagicMirror/js/app.js
- /MagicMirror/js/electron.js
- /MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function.<anonymous> (node:electron/js2c/browser_init:2:117419)
    at Module._resolveFilename (/MagicMirror/node_modules/module-alias/index.js:49:29)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/MagicMirror/modules/MMM-rdrDrawingBoard/node_helper.js:10:17)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at loadModule (/MagicMirror/js/app.js:180:19)
(Use `electron --trace-warnings ...` to show where the warning was created)
[05.11.2023 20:53.03.843] [ERROR] (node:2715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by Markdf68** [comment]
sorry i am new to Linux and node js i found that i did not install the request module.
